name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
          fail-fast: true
          matrix:
              os: [ubuntu-latest]
              php: [ 8.4, 8.3, 8.2 ]
              laravel: [ '10.*', '11.*', '12.*', '13.*' ]
              stability: [prefer-lowest, prefer-stable]
              include:
                  - laravel: 13.*
                    testbench: 11.*
                  - laravel: 12.*
                    testbench: 10.*
                  - laravel: 11.*
                    testbench: 9.*
                  - laravel: 10.*
                    testbench: 8.*

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: vendor/bin/phpunit --coverage-clover coverage.xml

    - name: Upload coverage to Scrutinizer
      if: matrix.php == '8.4' && matrix.laravel == '13.*' && matrix.stability == 'prefer-stable'
      uses: sudo-bot/action-scrutinizer@latest
      with:
        cli-args: "--format=php-clover coverage.xml --revision=${{ github.event.pull_request.head.sha || github.sha }}"
